version: '3'
services:
  jinux:
    build: .
    image: ${DOCKER_USER_ID}/jinux-hw4
  production:
    image: ${DOCKER_USER_ID}/jinux-hw4:${BUILD_NUMBER}
    volumes:
      - .:/code
      # - "./jenkins_home:/var/jenkins_home"
      # - "/var/run/docker.sock:/var/run/docker.sock"
    command: python main.py #runserver 8080:8080
    ports:
      - "8080:8080"