
version: '3'

services:

  jinux:
    container_name: jinux

    build: .

    image: ${DOCKER_USER_ID}/jinux-hw4

  production:

    image: ${DOCKER_USER_ID}/jinux-hw4:${BUILD_NUMBER}

    volumes:

      - .:/code

    command: python app.py

    ports:

      - "80:80"
