version: '3'
services:
  jinux:
    build: ./app
    image: ${DOCKER_USER_ID}/jinux-hw4
  production:
    image: ${DOCKER_USER_ID}/jinux-hw4:${BUILD_NUMBER}
    volumes:
     / - .:/code
    command: python main.py runserver 8080:8080
    ports:
      - "8080:8080"