version: '3.7'
services:
  jinux:
    container_name: jinux
    build: .
    image: ${DOCKER_USER_ID}/jinux-hw4
#     volumes:
#       - './jenkins_home:/var/jenkins_home'
#       - '/var/run/docker.sock:/var/run/docker.sock'
  production:
    image: ${DOCKER_USER_ID}/jinux-hw4
    # volumes:
    #   - ./app:/code
      # - "./jenkins_home:/var/jenkins_home"
      # - "/var/run/docker.sock:/var/run/docker.sock"
    # command: python main.py runserver 8080:8080
    ports:
      - "80:80"
