
version: '3'

services:

  jinux2:
    container_name: jinux2
    user : root
    build: .

    image: ${DOCKER_USER_ID}/jinux-hw4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /usr/bin/docker:/usr/bin/docker

    ports:

      - "8181:8181"
  production:

    image: ${DOCKER_USER_ID}/jinux-hw4:${BUILD_NUMBER}
    user : root

    #command: python app.py
