version: '3'
services:
  jinux:
    image: ${DOCKER_USER_ID}/jinux-hw4:latest
    /container_name: jinux
    build:
       context: .
    restart: always
  production:
    image: ${DOCKER_USER_ID}/jinux-hw4:${BUILD_NUMBER}
    volumes:
      - .:/code
    command: python app.py
    ports:
      - "80:80"
