
version: '3'

services:

  jinux:
    container_name: jinux
    user : root
    build: .

    image: ${DOCKER_USER_ID}/jinux-hw4
    volumes:
      - ~/docker/jenkins/var/jenkins_home:/var/jenkins_home

  #production:

   # image: ${DOCKER_USER_ID}/jinux-hw4:${BUILD_NUMBER}

    #command: python app.py

    #ports:

     # - "80:80"
